# 01 - Exploratory Data Analysis

**Project**: Flu Shot Learning: Predict H1N1 and Seasonal Flu Vaccines

**Author**: Jarret Angbazo

**Date**: May 10, 2026

---

## Objective
Explore our dataset to understand:
- Data structure and quality
- Distribution of our target variables (h1n1_vaccine/seasonal_vaccine)
- Relationship between features and targets
- Differences between the target variables

## 1. Setup and Imports

In [165]:
# Standard libraries
import numpy as np
import pandas as pd
from pathlib import Path

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

# Settings
pd.set_option('display.max_columns', None)
sns.set_style('whitegrid')
plt.rcParams['figure.figsize'] = (12, 6)

# Warnings
import warnings
warnings.filterwarnings('ignore')

%matplotlib inline
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

## 2. Load Data

In [188]:
# Define paths
DATA_PATH = Path('../data/raw')

# Load training features and labels
flu_features_train = pd.read_csv(DATA_PATH / 'training_set_features.csv')
flu_labels_train = pd.read_csv(DATA_PATH / 'training_set_labels.csv')

# Load test features
flu_features_test = pd.read_csv(DATA_PATH / 'test_set_features.csv')

In [528]:
# Inspect flu train features dataframe
print(flu_features_train.shape)         # Check the shape of the training features dataframe
flu_features_train.head()

(26707, 36)

,respondent_id,h1n1_concern,h1n1_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,doctor_recc_h1n1,doctor_recc_seasonal,chronic_med_condition,child_under_6_months,health_worker,health_insurance,opinion_h1n1_vacc_effective,opinion_h1n1_risk,opinion_h1n1_sick_from_vacc,opinion_seas_vacc_effective,opinion_seas_risk,opinion_seas_sick_from_vacc,age_group,education,race,sex,income_poverty,marital_status,rent_or_own,employment_status,hhs_geo_region,census_msa,household_adults,household_children,employment_industry,employment_occupation
0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,1.0,2.0,2.0,1.0,2.0,55 - 64 Years,< 12 Years,White,Female,Below Poverty,Not Married,Own,Not in Labor Force,oxchjgsf,Non-MSA,0.0,0.0,NaN,NaN
1,1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,5.0,4.0,4.0,4.0,2.0,4.0,35 - 44 Years,12 Years,White,Male,Below Poverty,Not Married,Rent,Employed,bhuqouqj,"MSA, Not Principle City",0.0,0.0,pxcmvdjn,xgwztkwe
2,2,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,1.0,0.0,0.0,NaN,3.0,1.0,1.0,4.0,1.0,2.0,18 - 34 Years,College Graduate,White,Male,"<= $75,000, Above Poverty",Not Married,Own,Employed,qufhixun,"MSA, Not Principle City",2.0,0.0,rucpziij,xtkaffoo
3,3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,NaN,3.0,3.0,5.0,5.0,4.0,1.0,65+ Years,12 Years,White,Female,Below Poverty,Not Married,Rent,Not in Labor Force,lrircsnp,"MSA, Principle City",0.0,0.0,NaN,NaN
4,4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,3.0,3.0,2.0,3.0,1.0,4.0,45 - 54 Years,Some College,White,Female,"<= $75,000, Above Poverty",Married,Own,Employed,qufhixun,"MSA, Not Principle City",1.0,0.0,wxleyezf,emcorrxb

In [529]:
print(flu_features_train['respondent_id'].duplicated().sum())     # Check for duplicate respondent_id
print(flu_features_train['respondent_id'].isnull().sum())         # Check for missing respondent_id

# If duplicate respondent_id exists, list them to investigate further
if flu_features_train['respondent_id'].duplicated().any():
    print('Duplicated respondent_id:')
    print(flu_features_train[flu_features_train['respondent_id'].duplicated(keep=False)]['respondent_id'])
else:
    print('No duplicated respondent_id found.')

# If missing respondent_id exists, list them to investigate further
if flu_features_train['respondent_id'].isnull().any():
    print('Missing respondent_id:')
    print(flu_features_train[flu_features_train['respondent_id'].isnull()])
else:
    print('No missing respondent_id found.')

0
0
No duplicated respondent_id found.
No missing respondent_id found.

In [554]:
# Inspect flu train labels dataframe
print(flu_labels_train.shape)           # Check the shape of the training labels dataframe
flu_labels_train.head()

(26707, 3)

   respondent_id  h1n1_vaccine  seasonal_vaccine
0              0             0                 0
1              1             0                 1
2              2             0                 0
3              3             0                 1
4              4             0                 0

In [555]:
print(flu_labels_train['respondent_id'].duplicated().sum())     # Check for duplicate respondent_id
print(flu_labels_train['respondent_id'].isnull().sum())         # Check for missing respondent_id

# Check distribution of target variables
print(flu_labels_train['h1n1_vaccine'].value_counts())          # h1n1_vaccine distribution
print(flu_labels_train['seasonal_vaccine'].value_counts())      # seasonal_vaccine distribution

0
0
h1n1_vaccine
0    21033
1     5674
Name: count, dtype: int64
seasonal_vaccine
0    14272
1    12435
Name: count, dtype: int64

In [578]:
# Inspect flu test features dataframe
print(flu_features_test.shape)        # Check the shape of the test features dataframe
flu_features_test.head()

(26708, 36)

,respondent_id,h1n1_concern,h1n1_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,doctor_recc_h1n1,doctor_recc_seasonal,chronic_med_condition,child_under_6_months,health_worker,health_insurance,opinion_h1n1_vacc_effective,opinion_h1n1_risk,opinion_h1n1_sick_from_vacc,opinion_seas_vacc_effective,opinion_seas_risk,opinion_seas_sick_from_vacc,age_group,education,race,sex,income_poverty,marital_status,rent_or_own,employment_status,hhs_geo_region,census_msa,household_adults,household_children,employment_industry,employment_occupation
0,26707,2.0,2.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,5.0,1.0,1.0,5.0,1.0,1.0,35 - 44 Years,College Graduate,Hispanic,Female,"> $75,000",Not Married,Rent,Employed,mlyzmhmf,"MSA, Not Principle City",1.0,0.0,atmlpfrs,hfxkjkmi
1,26708,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,1.0,1.0,4.0,1.0,1.0,18 - 34 Years,12 Years,White,Male,Below Poverty,Not Married,Rent,Employed,bhuqouqj,Non-MSA,3.0,0.0,atmlpfrs,xqwwgdyp
2,26709,2.0,2.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,5.0,4.0,2.0,5.0,4.0,4.0,55 - 64 Years,College Graduate,White,Male,"> $75,000",Married,Own,Employed,lrircsnp,Non-MSA,1.0,0.0,nduyfdeo,pvmttkik
3,26710,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,4.0,2.0,2.0,4.0,4.0,2.0,65+ Years,12 Years,White,Female,"<= $75,000, Above Poverty",Married,Own,Not in Labor Force,lrircsnp,"MSA, Not Principle City",1.0,0.0,NaN,NaN
4,26711,3.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,5.0,2.0,4.0,4.0,4.0,2.0,35 - 44 Years,12 Years,Black,Female,"<= $75,000, Above Poverty",Not Married,Own,Employed,lzgpxyit,Non-MSA,0.0,1.0,fcxhlnwr,mxkfnird

In [600]:
print(flu_features_test['respondent_id'].duplicated().sum())     # Check for duplicate respondent_id
print(flu_features_test['respondent_id'].isnull().sum())         # Check for missing respondent_id

# If duplicate respondent_id exists, list them to investigate further
if flu_features_test['respondent_id'].duplicated().any():
    print('Duplicated respondent_id:')
    print(flu_features_test[flu_features_test['respondent_id'].duplicated(keep=False)]['respondent_id'])
else:
    print('No duplicated respondent_id found.')

# If missing respondent_id exists, list them to investigate further
if flu_features_test['respondent_id'].isnull().any():
    print('Missing respondent_id:')
    print(flu_features_test[flu_features_test['respondent_id'].isnull()])
else:
    print('No missing respondent_id found.')

0
0
No duplicated respondent_id found.
No missing respondent_id found.

In [ ]:
# Merge training features and labels dataframes
flu_train_merged = flu_features_train.merge(flu_labels_train, on='respondent_id')
flu_train_merged.head()

,respondent_id,h1n1_concern,h1n1_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,doctor_recc_h1n1,doctor_recc_seasonal,chronic_med_condition,child_under_6_months,health_worker,health_insurance,opinion_h1n1_vacc_effective,opinion_h1n1_risk,opinion_h1n1_sick_from_vacc,opinion_seas_vacc_effective,opinion_seas_risk,opinion_seas_sick_from_vacc,age_group,education,race,sex,income_poverty,marital_status,rent_or_own,employment_status,hhs_geo_region,census_msa,household_adults,household_children,employment_industry,employment_occupation,h1n1_vaccine,seasonal_vaccine
0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,1.0,2.0,2.0,1.0,2.0,55 - 64 Years,< 12 Years,White,Female,Below Poverty,Not Married,Own,Not in Labor Force,oxchjgsf,Non-MSA,0.0,0.0,NaN,NaN,0,0
1,1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,5.0,4.0,4.0,4.0,2.0,4.0,35 - 44 Years,12 Years,White,Male,Below Poverty,Not Married,Rent,Employed,bhuqouqj,"MSA, Not Principle City",0.0,0.0,pxcmvdjn,xgwztkwe,0,1
2,2,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,1.0,0.0,0.0,NaN,3.0,1.0,1.0,4.0,1.0,2.0,18 - 34 Years,College Graduate,White,Male,"<= $75,000, Above Poverty",Not Married,Own,Employed,qufhixun,"MSA, Not Principle City",2.0,0.0,rucpziij,xtkaffoo,0,0
3,3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,NaN,3.0,3.0,5.0,5.0,4.0,1.0,65+ Years,12 Years,White,Female,Below Poverty,Not Married,Rent,Not in Labor Force,lrircsnp,"MSA, Principle City",0.0,0.0,NaN,NaN,0,1
4,4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,3.0,3.0,2.0,3.0,1.0,4.0,45 - 54 Years,Some College,White,Female,"<= $75,000, Above Poverty",Married,Own,Employed,qufhixun,"MSA, Not Principle City",1.0,0.0,wxleyezf,emcorrxb,0,0

## 3. Initial Data Inspection

In [662]:
# Display basic information
# TODO: Show shape, dtypes, first few rows

print(flu_train_merged.shape)  # Shape of the merged training dataframe

print(flu_train_merged.dtypes) # dtypes of each column

# First few rows of merged training dataframe
flu_train_merged.head()

(26707, 38)
respondent_id                    int64
h1n1_concern                   float64
h1n1_knowledge                 float64
behavioral_antiviral_meds      float64
behavioral_avoidance           float64
behavioral_face_mask           float64
behavioral_wash_hands          float64
behavioral_large_gatherings    float64
behavioral_outside_home        float64
behavioral_touch_face          float64
doctor_recc_h1n1               float64
doctor_recc_seasonal           float64
chronic_med_condition          float64
child_under_6_months           float64
health_worker                  float64
health_insurance               float64
opinion_h1n1_vacc_effective    float64
opinion_h1n1_risk              float64
opinion_h1n1_sick_from_vacc    float64
opinion_seas_vacc_effective    float64
opinion_seas_risk              float64
opinion_seas_sick_from_vacc    float64
age_group                       object
education                       object
race                            object
sex                             object
income_poverty                  object
marital_status                  object
rent_or_own                     object
employment_status               object
hhs_geo_region                  object
census_msa                      object
household_adults               float64
household_children             float64
employment_industry             object
employment_occupation           object
h1n1_vaccine                     int64
seasonal_vaccine                 int64
dtype: object

,respondent_id,h1n1_concern,h1n1_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,doctor_recc_h1n1,doctor_recc_seasonal,chronic_med_condition,child_under_6_months,health_worker,health_insurance,opinion_h1n1_vacc_effective,opinion_h1n1_risk,opinion_h1n1_sick_from_vacc,opinion_seas_vacc_effective,opinion_seas_risk,opinion_seas_sick_from_vacc,age_group,education,race,sex,income_poverty,marital_status,rent_or_own,employment_status,hhs_geo_region,census_msa,household_adults,household_children,employment_industry,employment_occupation,h1n1_vaccine,seasonal_vaccine
0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,1.0,2.0,2.0,1.0,2.0,55 - 64 Years,< 12 Years,White,Female,Below Poverty,Not Married,Own,Not in Labor Force,oxchjgsf,Non-MSA,0.0,0.0,NaN,NaN,0,0
1,1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,5.0,4.0,4.0,4.0,2.0,4.0,35 - 44 Years,12 Years,White,Male,Below Poverty,Not Married,Rent,Employed,bhuqouqj,"MSA, Not Principle City",0.0,0.0,pxcmvdjn,xgwztkwe,0,1
2,2,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,1.0,0.0,0.0,NaN,3.0,1.0,1.0,4.0,1.0,2.0,18 - 34 Years,College Graduate,White,Male,"<= $75,000, Above Poverty",Not Married,Own,Employed,qufhixun,"MSA, Not Principle City",2.0,0.0,rucpziij,xtkaffoo,0,0
3,3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,NaN,3.0,3.0,5.0,5.0,4.0,1.0,65+ Years,12 Years,White,Female,Below Poverty,Not Married,Rent,Not in Labor Force,lrircsnp,"MSA, Principle City",0.0,0.0,NaN,NaN,0,1
4,4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,3.0,3.0,2.0,3.0,1.0,4.0,45 - 54 Years,Some College,White,Female,"<= $75,000, Above Poverty",Married,Own,Employed,qufhixun,"MSA, Not Principle City",1.0,0.0,wxleyezf,emcorrxb,0,0

In [665]:
# Check for missing values
# TODO: Visualize missing data patterns

In [666]:
# Summary statistics
# TODO: Display descriptive statistics

## 4. Target Variable Analysis

In [667]:
# Distribution of total_cases
# TODO: Create histogram/distribution plot

In [668]:
# Total cases by city
# TODO: Compare distributions between San Juan and Iquitos

In [669]:
# Statistical summary of target by city
# TODO: Calculate mean, median, std, min, max for each city

## 5. Temporal Analysis

In [670]:
# Time series plot of cases
# TODO: Plot total_cases over time for each city

In [671]:
# Seasonality analysis
# TODO: Analyze cases by month, quarter, or week of year

In [672]:
# Year-over-year trends
# TODO: Compare patterns across years

## 6. Feature Analysis

In [673]:
# Correlation analysis
# TODO: Create correlation heatmap of all features

In [674]:
# Feature correlation with target
# TODO: Identify features most correlated with total_cases

In [675]:
# Temperature features analysis
# TODO: Explore temperature variables (avg, min, max)

In [676]:
# Precipitation features analysis
# TODO: Explore precipitation variables

In [677]:
# Vegetation index (NDVI) analysis
# TODO: Explore vegetation features

## 7. Bivariate Analysis

In [678]:
# Scatter plots: features vs target
# TODO: Create scatter plots for key features

In [679]:
# Feature interactions
# TODO: Explore temperature-humidity, precipitation-vegetation interactions

## 8. City Comparison

In [680]:
# Compare climate patterns between cities
# TODO: Side-by-side comparison of San Juan vs Iquitos

In [681]:
# Feature distributions by city
# TODO: Create distribution plots for each city

## 9. Key Findings & Insights

### Summary of Findings:
1. **Data Quality**: 
   - TODO: Document missing data patterns
   - TODO: Note any data quality issues

2. **Target Variable**:
   - TODO: Describe distribution characteristics
   - TODO: Note city differences

3. **Temporal Patterns**:
   - TODO: Describe seasonality
   - TODO: Note trends over time

4. **Feature Relationships**:
   - TODO: List most important features
   - TODO: Note interesting correlations

### Implications for Modeling:
- TODO: What preprocessing is needed?
- TODO: What features should be engineered?
- TODO: Should cities be modeled separately?
- TODO: What model types might work well?

## 10. Next Steps

Based on this EDA:
1. TODO: Data cleaning priorities
2. TODO: Feature engineering ideas
3. TODO: Modeling approach considerations